// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eecuhngmqvzhhmywqnjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlY3VobmdtcXZ6aGhteXdxbmpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MzM3MjUsImV4cCI6MjA2NTAwOTcyNX0.U4wnmBgmeq2PlSF5XJfmNEYL_ogQgu-GHK0jBM7Hlmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);